fix: Hardened the Docker context checking logic

diff --git a/sections/sz::docker b/sections/sz::docker
--- a/sections/sz::docker
+++ b/sections/sz::docker
@@ -62,7 +62,8 @@ sz::docker() {
 
   # if docker daemon isn't running you'll get an error saying it can't connect
   local docker_version=$(docker version -f "{{.Server.Version}}" 2>/dev/null | head -n 1)
-  [[ -z $docker_version ]] && return
+  # Note: Declaration and assignment is separated for correctly getting the exit code
+  [[ $? -ne 0 || -z $docker_version ]] && return
 
   [[ $SPACESHIP_DOCKER_VERBOSE == false ]] && docker_version=${docker_version%-*}
 
@@ -86,12 +87,13 @@ sz::docker() {
       # or the `docker context use` command. `docker context ls` will show the selected
       # context in both cases. But we are not interested in the local "default" context.
       docker_remote_context=$(docker context ls --format '{{if .Current}}{{if ne .Name "default"}}{{.Name}}{{end}}{{end}}' 2>/dev/null)
+      [[ $? -ne 0 ]] && return
       docker_remote_context=${docker_remote_context//$'\n'}
     fi
     [[ -n $docker_remote_context ]] && \
-      docker_remote_context="${SPACESHIP_DOCKER_CONTEXT_PREFIX}${docker_remote_context}${SPACESHIP_DOCKER_CONTEXT_SUFFIX}" 
+      docker_remote_context="${SPACESHIP_DOCKER_CONTEXT_PREFIX}${docker_remote_context}${SPACESHIP_DOCKER_CONTEXT_SUFFIX}"
   fi
-  
+
   if [[ -z $docker_version && -z $docker_remote_context ]]; then
     return
   elif [[ -n $docker_version && -n $docker_remote_context ]]; then
